django/belt_reviewer/apps/books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^new$', views.new, name="new_book"),
    url(r'^create$', views.create_book, name="create_book"),
    url(r'^(?P<book_id>\d+)$', views.show_book, name='show_book'),
]

django/belt_reviewer/apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="homepage"),
    url(r'^register$', views.register),
    url(r'^login$', views.login),
    url(r'^profile$', views.show_user, name="show_user"),
    url(r'^logout$', views.logout, name="logout"),
]

django/belt_reviewer/belt_reviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('apps.books.urls', namespace='books')),
    url(r'^', include('apps.users.urls', namespace='users'))
]

django/belt_reviewer/apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):
    #validates login AND registration
    def basic_validator(self, postData, action):
        errors = []
        # checks if user is registering
        if action == 'register':
            if len(postData['first_name']) < 1:
                errors.append("Please put in a first name!")
            if len(postData['last_name']) < 1:
                errors.append("Please put in a last name!")
            if len(postData['email']) < 1:
                errors.append("Please enter an email!")
            if not EMAIL_REGEX.match(postData['email']):
                errors.append("Please enter a valid email!")
            if len(postData['password']) < 8:
                errors.append("Please enter a password!")
            if postData['conf_pw'] != postData['password']:
                errors.append("Password must match!!")
        elif action == 'login':
            if len(postData['email']) < 1:
                errors.append("Please enter your email!")
            elif not EMAIL_REGEX.match(postData['email']):
                errors.append("Please enter a valid email!")

        email_exists = User.objects.filter(email_address=postData['email'])

        if not errors:
            # checks if user is registering
            if action == 'register':
                if len(email_exists) != 0:
                    # checks if registering user email already exists
                    errors.append('This user exists!')
                    return (False, errors)
                #otherwise bcrypt password and create user
                hashed_pw = bcrypt.hashpw(
                    postData['password'].encode(), bcrypt.gensalt())
                user = User.objects.create(
                    first_name=postData['first_name'],
                    last_name=postData['last_name'],
                    email_address=postData['email'],
                    password=hashed_pw
                )
                return (True, user)
            elif action == 'login':
                #compares user password with posted password
                correct_pw = bcrypt.checkpw(postData['user_password'].encode(), email_exists[0].password.encode())
                #checks if user logging in exists
                if len(email_exists) == 0:
                    #validates whether user actually exists
                    errors.append(
                        "This user either doesn't exist or the password is wrong... figure it out.")
                    return (False, errors)
                if correct_pw:
                    user_id = email_exists[0].id
                    return (True, user_id)
                errors.append(
                    "This user either doesn't exist or the password is wrong... figure it out.")
                return (False, errors)
        return (False, errors)


class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email_address = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

django/belt_reviewer/apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from .models import User
from ..books.models import Book, Review
from django.contrib import messages

# Create your views here.
def index(request):

    if 'id' in request.session:
        return redirect('users:show_user')

    return render(request, 'users/index.html')

def register(request):
    if 'name' not in request.session:
        print "trying to register"
        valid, response = User.objects.basic_validator(request.POST, 'register')
        print response
        if not valid:
            for error in response:
                messages.error(request, error)
            return redirect('users:homepage')
        request.session['name'] = request.POST['first_name']
        #how can we get id from newly registered users? 
        request.session['id'] = response.id
        return redirect('users:show_user')

def login(request):
    if 'name' not in request.session:
        valid, response = User.objects.basic_validator(request.POST, 'login')
        if not valid:
            for error in response:
                messages.error(request, error)
            return redirect('users:homepage')
        logged_in_user = User.objects.get(id=response)
        request.session['name'] = logged_in_user.first_name
        request.session['id'] = logged_in_user.id
        #be sure to store id so when user creates something we can tie it to a foreign key. Also avoids confusing people with same name
        return redirect('users:show_user')
    return redirect('users:homepage')


def logout(request):
    request.session.clear()

    return redirect('users:homepage')

def show_user(request):
    if 'id' not in request.session:
        messages.error(request, 'Please Login or Register!')
        return redirect('users:homepage')
    user = User.objects.get(id=request.session['id'])
    unique_ids = user.reviews_left.all().values("book").distinct()
    unique_books = []
    for book in unique_ids:
        unique_books.append(Book.objects.get(id=book['book']))
    recent_reviews = Review.objects.recent_and_not
    print recent_reviews
    context = {
        'user': user,
        'user_reviews': unique_books,
        'recent': recent_reviews
    }
    return render(request, 'users/users.html', context)

django/belt_reviewer/apps/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
        crossorigin="anonymous">
     {% load static %}
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}" media="screen" title="no title" charset="utf-8">
    <title>Login and Registration</title>
</head>
<body>
    <div class="container">
        <div class="header page-header">
            <h1>Belt Reviewer</h1>
            <p class="float-right">Welcome! Review Books... even if they don't exist!</p>
        </div>
        <div class="login-reg">
            <div class="registration form-group">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <p>{{ message }}</p>
                    {% endfor %}
                </ul>
            {% endif %}
                <form action='register' method='post'>
                    {% csrf_token %}
                    <label for="first_name">First Name:</label>
                    <input type="text" name="first_name" class="form-control">
                    <label for="last_name">Last Name:</label>
                    <input type="text" name="last_name" class="form-control">
                    <label for="email">Email:</label>
                    <input type="text" name="email" class="form-control">
                    <label for="password">Password:</label>
                    <input type="password" name="password" class="form-control">
                    <label for="conf_pw">Confirm Password:</label>
                    <input type="password" name="conf_pw" class="form-control">
                    <br>
                    <input type="submit" name="register" value="Register Now!">
                </form>
            </div>
            <div class="login form-group float-right">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <p>{{ message }}</p>
                    {% endfor %}
                </ul>
            {% endif %}
                <form action='login' method='post'>
                    {% csrf_token %}
                    <label for="user_name">Email:</label>
                    <input type="text" name="email" class="form-control">
                    <label for="password">Password:</label>
                    <input type="password" name="user_password" class="form-control">
                    <br>
                    <input type="submit" name="login" value="Login">
                </form>
            </div>
        </div>
    </div>
</body>
</html>

django/belt_reviewer/apps/users/templates/users/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
        crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}" media="screen" title="no title" charset="utf-8">
    <title>{{user.first_name}}'s Reviews</title>
</head>
<body>
    <div class="container">
        <div class="header page-header">
            <h1>Belt Reviewer</h1>
            <a href="{% url 'users:logout' %}" class="float-right">Logout</a>
        </div>
        <h2>Welcome, {{user.first_name}}.</h2>
        <a href="{% url 'books:new_book' %}">Add a new book</a> 
        <h2><strong>Total Reviews: </strong> {{user.reviews_left.all.count}}</h2>
        <hr>
        <h2>Thanks for Posting Reviews on the Following Books:</h2>
        {% for book in user_reviews %}
            <h4><a href="/books/{{book.id}}">{{book.title}}</a></h4>
        {% endfor %}
        {% for review in recent %}
            {{recent}}
        {% endfor %}
    </div>
</body>
</html>